grpc:
  client:

    # grpc ? client - server ???? ??????? ??? ?? ??? ??
    calculator-server: # calculator-server ?? ???? ???
      address: "static://localhost:9090" # dns ??? ??? ?? ??
      negotiationType: plaintext # TLS ?? x ?? HTTP/2 ? ?????.